### ISSUE TITLE
Wont boot on 1.13.2

### ISSUE THREAD

**Issue by Lumince** [eccentricdevotion/ItemSlotMachine#2]
Would you be willing to build this plugin to work on 1.13.2? I was on 1.14.4 but its just so unstable... I tried to build it with the 1.13.2 API but it still complains that it only works for 1.14 :(

**Comment by eccentricdevotion** [comment]
https://github.com/eccentricdevotion/ItemSlotMachine/releases/tag/v1.3.13

**Comment by Lumince** [comment]
My bad! It works after deleting some config files! Thank you <3
