### ISSUE TITLE
Spamming the console.

### ISSUE THREAD

**Issue by BingooDev** [eccentricdevotion/ItemSlotMachine#4]
Please don't log all messages and sign updates to the console.

Change MessageManager:167 from
`System.out.println("Message :" + message);`
to
```
if (Settings.isDebugModeEnabled()) {
      	System.out.println("Message :" + message);
}
```
and
SignUpdater:52 from
`System.out.println("After Line " + i + ":" + lines[i]);`
to
```
if (Settings.isDebugModeEnabled()) {
       	System.out.println("After Line " + i + ":" + lines[i]);
 }
```

**Comment by eccentricdevotion** [comment]
Turn off debug mode in the config - `Debug_Mode_Enabled: false`

**Comment by eccentricdevotion** [comment]
https://github.com/eccentricdevotion/ItemSlotMachine/releases/tag/v1.4
