### ISSUE TITLE
Please Update to 1.15.2

### ISSUE THREAD

**Issue by BobbyTowers** [eccentricdevotion/ItemSlotMachine#5]
Can you update? I can give you some cash!?

**Comment by eccentricdevotion** [comment]
It's already updated to 1.15.1 there won't be any code changes between that and 1.15.2...

**Comment by eccentricdevotion** [comment]
http://tardisjenkins.duckdns.org:8080/job/ItemSlotMachine/

**Comment by BobbyTowers** [comment]
THANK YOU!
